In [ ]:
# import packages and utilities
import pandas as pd

In [ ]:
# load data and preprocess
conference_2005 = pd.read_csv('./input/2005/conference.csv')
drive_2005 = pd.read_csv('./input/2005/drive.csv')
game_statistics_2005 = pd.read_csv('./input/2005/game-statistics.csv')
game_2005 = pd.read_csv('./input/2005/game.csv')
kickoff_return_2005 = pd.read_csv('./input/2005/kickoff-return.csv')
kickoff_2005 = pd.read_csv('./input/2005/kickoff.csv')
pass_2005 = pd.read_csv('./input/2005/pass.csv')
play_2005 = pd.read_csv('./input/2005/play.csv')
player_game_statistics_2005 = pd.read_csv('./input/2005/player-game-statistics.csv')
player_2005 = pd.read_csv('./input/2005/player.csv')
punt_return_2005 = pd.read_csv('./input/2005/punt-return.csv')
punt_2005 = pd.read_csv('./input/2005/punt.csv')
reception_2005 = pd.read_csv('./input/2005/reception.csv')
rush_2005 = pd.read_csv('./input/2005/rush.csv')
stadium_2005 = pd.read_csv('./input/2005/stadium.csv')
team_game_statistics_2005 = pd.read_csv('./input/2005/team-game-statistics.csv')
team_2005 = pd.read_csv('./input/2005/team.csv')

In [ ]:
game_2005

In [ ]:
# utility functions to load and transform the data
def concat_mult_ref_tables(filename, yrs):
    """Return a dataframe that concatenates all 
    files across a list of years, with the year set as a key
    """
    # create a list to store the dfs
    df_list = []
    
    for yr in yrs: 
        temp_df = None   #clear out the df
        temp_df = pd.read_csv('./input/' + str(yr) + '/conference.csv')  #read in the file
        df_list.append(temp_df)
        
    final_df = pd.concat(df_list, keys=yrs)
    
    return final_df

In [ ]:
team_2005[team_2005['Name'] == 'Florida']

In [ ]:
team_2005[team_2005['Team Code'] == 234]

In [ ]:
# create some new useful datasets
tmp_col_list = ['Team Code', 'Game Code', 'Points']
team_points = team_game_statistics_2005[tmp_col_list]

# produce a new dataset called game_results that tells us who won each game
game_results_2005 = game_2005
game_results_2005['Visit Points'] = None
game_results_2005['Home Points'] = None
game_results_2005['Home Team Winner'] = None
game_results_2005['Final Spread'] = None
game_results_2005['Total Points'] = None
for index, row in game_results_2005.iterrows():
    # find the visiting team's points
    visit_pts_ix = team_points.index[(team_points['Team Code']==row['Visit Team Code']) 
                    & (team_points['Game Code']==row['Game Code'])].tolist()
    visit_pts = team_points.loc[visit_pts_ix[0]].at['Points']
    # find the home team's points
    home_pts_ix = team_points.index[(team_points['Team Code']==row['Home Team Code']) 
                    & (team_points['Game Code']==row['Game Code'])].tolist()
    home_pts = team_points.loc[home_pts_ix[0]].at['Points']
    # calculate the spread and total points
    final_spread = abs(home_pts - visit_pts)
    total_pts = home_pts + visit_pts
    
    # save all values to the game_results dataset
    game_results_2005.loc[index, 'Visit Points'] = visit_pts
    game_results_2005.loc[index, 'Home Points'] = home_pts
    game_results_2005.loc[index, 'Final Spread'] = final_spread
    game_results_2005.loc[index, 'Total Points'] = total_pts
    if home_pts > visit_pts:
        game_results_2005.loc[index, 'Home Team Winner'] = 1
    else:
        game_results_2005.loc[index, 'Home Team Winner'] = 0

In [ ]:
game_results_2005

In [ ]:
game_results_2005.Site.unique()

In [ ]:
game_2005

In [19]:
import pandas as pd
past_games = pd.read_csv('/Users/markvonoven/Projects/CollegeFootball/SRoutput/past_games_w_SRGLfeatures.csv')
SOS = pd.read_csv('/Users/markvonoven/Projects/CollegeFootball/SRinput/current/past_games.csv')
cols = ['Season', 'Gamecode', 'Team_SOS', 'Opp_SOS']
SOS = SOS[cols]
SOS.set_index(['Season', 'Gamecode'], inplace=True)

In [20]:
past_games.set_index(['Season', 'Gamecode'], inplace=True)
past_games.tail()

                                     Date          Team           Opp  Won  \
Season Gamecode
2018   2018121PitCle  2018-12-01 20:00:00    Pittsburgh       Clemson    0
       2018121OhiNor  2018-12-01 20:00:00    Ohio State  Northwestern    1
       2018121NorOhi  2018-12-01 20:00:00  Northwestern    Ohio State    0
       2018128ArmNav  2018-12-08 15:00:00          Army          Navy    1
       2018128NavArm  2018-12-08 15:00:00          Navy          Army    0

                     Game_home  Team_rank  Opp_rank  Game_conf  Team_SRTD  \
Season Gamecode
2018   2018121PitCle      Away       0.00      0.92          1      0.583
       2018121OhiNor      Home       0.76      0.16          1      0.917
       2018121NorOhi      Away       0.16      0.76          1      0.667
       2018128ArmNav      Home       0.12      0.00          0      0.818
       2018128NavArm      Away       0.00      0.12          0      0.250

                      Team_CRTD  Opp_SRTD  Opp_CRTD  Team_OffStrat  \
Season Gamecode
2018   2018121PitCle      0.750     1.000     1.000          0.563
       2018121OhiNor      0.889     0.667     0.889          0.980
       2018121NorOhi      0.889     0.917     0.889          0.998
       2018128ArmNav      1.000     0.250     0.286          0.119
       2018128NavArm      0.286     0.818     1.000          0.162

                      Opp_OffStrat  Team_DefStren  Opp_DefStren
Season Gamecode
2018   2018121PitCle         0.886          1.287         2.163
       2018121OhiNor         0.998          1.467         1.767
       2018121NorOhi         0.980          1.767         1.467
       2018128ArmNav         0.162          1.830         1.314
       2018128NavArm         0.119          1.314         1.830

In [21]:
SOS.tail()

                      Team_SOS  Opp_SOS
Season Gamecode
2018   2018121PitCle     0.616    0.598
       2018121OhiNor     0.515    0.544
       2018121NorOhi     0.544    0.515
       2018128ArmNav     0.553    0.582
       2018128NavArm     0.582    0.553

In [24]:
past_games = past_games.join(SOS)
past_games['Date'] = pd.to_datetime(past_games['Date'])
past_games = past_games.sort_values(by=['Date'])

In [27]:
past_games.to_csv('/Users/markvonoven/Projects/CollegeFootball/SRoutput/past_games_w_SOS.csv')