# Model Scoring

In [ ]:
from jobs import SRmodel
from sklearn.model_selection import train_test_split
import pandas as pd

schedule_mstr = pd.read_csv('./SRinput/current/past_games.csv')

features = schedule_mstr.columns[6:]

y = schedule_mstr.Won
X = schedule_mstr[features]

train_X, val_X, train_y, val_y = train_test_split(X,y,random_state=1)

In [ ]:
schedule_mstr

In [ ]:
SRmodel.score_XGB(train_X, train_y, val_X, val_y)

In [ ]:
SRmodel.save_XGB(X, y)

In [ ]:
SRmodel.score_Keras(X, y)

In [ ]:
SRmodel.scorensave_Keras(X, y)

# Model Predictions

### XGBoost and Keras together

In [4]:
from jobs import SRmodel
XG = SRmodel.predict_XGB()
KS = SRmodel.predict_Keras()
Pred_final = XG.copy()
Pred_final['Keras'] = KS['Prediction']
Pred_final['Keras_proba'] = KS['Proba']
Pred_final.columns = ['Date', 'Team', 'Opp', 'XG', 'Keras', 'Keras_proba']
Pred_final

,Date,Team,Opp,XG,Keras,Keras_proba
0,2018-11-30 19:00:00,Buffalo,Northern Illinois,1,1.0,0.712283
1,2018-11-30 20:00:00,Utah,Washington,0,0.0,0.479492
2,2018-12-01 12:00:00,Akron,South Carolina,0,0.0,0.199342
3,2018-12-01 16:00:00,Alabama,Georgia,1,1.0,0.780219
4,2018-12-01 13:30:00,Alabama-Birmingham,Middle Tennessee State,0,0.0,0.249796
5,2018-12-01 20:00:00,Clemson,Pittsburgh,1,1.0,0.957843
6,2018-12-01 12:00:00,Drake,Iowa State,0,0.0,0.039457
7,2018-12-01 12:00:00,East Carolina,North Carolina State,0,0.0,0.118170
8,2018-12-01 19:45:00,Fresno State,Boise State,0,0.0,0.332354
9,2018-12-01 12:00:00,Louisiana,Appalachian State,0,0.0,0.291955
10,2018-12-01 12:00:00,Marshall,Virginia Tech,0,0.0,0.403626
11,2018-12-01 15:30:00,Memphis,Central Florida,0,0.0,0.074584
12,2018-12-01 14:00:00,Norfolk State,Liberty,0,0.0,0.066692
13,2018-12-01 20:00:00,Northwestern,Ohio State,0,0.0,0.313826
14,2018-12-01 12:00:00,Oklahoma,Texas,1,1.0,0.769352
15,2018-12-01 15:00:00,Stanford,California,0,0.0,0.488701
16,2018-12-08 15:00:00,Army,Navy,1,1.0,0.903325